/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jui
 */
public class Dashboard extends javax.swing.JFrame {

    
    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
        refresh();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblRooms = new javax.swing.JTable();
        btnSettings = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        btnAddUser = new javax.swing.JButton();
        btnAlloteRoom = new javax.swing.JButton();
        btnDeallocate = new javax.swing.JButton();
        btnAddRoom = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Dashboard");
        setMinimumSize(new java.awt.Dimension(960, 470));
        setResizable(false);
        getContentPane().setLayout(null);

        tblRooms.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Room ID", "Gender", "Status", "Current Guest", "Fee", "Information"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblRooms);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 60, 940, 370);

        btnSettings.setIcon(new javax.swing.ImageIcon(getClass().getResource("/settings.png"))); // NOI18N
        btnSettings.setText("Settings");
        btnSettings.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSettingsMouseClicked(evt);
            }
        });
        btnSettings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSettingsActionPerformed(evt);
            }
        });
        getContentPane().add(btnSettings);
        btnSettings.setBounds(800, 10, 150, 40);

        btnRefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/circular-arrow.png"))); // NOI18N
        btnRefresh.setText("Refresh");
        btnRefresh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRefreshMouseClicked(evt);
            }
        });
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });
        getContentPane().add(btnRefresh);
        btnRefresh.setBounds(640, 10, 150, 40);

        btnAddUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/add-user.png"))); // NOI18N
        btnAddUser.setText("Add User");
        btnAddUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddUserMouseClicked(evt);
            }
        });
        btnAddUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddUserActionPerformed(evt);
            }
        });
        getContentPane().add(btnAddUser);
        btnAddUser.setBounds(480, 10, 150, 40);

        btnAlloteRoom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/check-mark.png"))); // NOI18N
        btnAlloteRoom.setText("Allote Room");
        btnAlloteRoom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAlloteRoomMouseClicked(evt);
            }
        });
        btnAlloteRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlloteRoomActionPerformed(evt);
            }
        });
        getContentPane().add(btnAlloteRoom);
        btnAlloteRoom.setBounds(170, 10, 140, 40);

        btnDeallocate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/close.png"))); // NOI18N
        btnDeallocate.setText("Deallote Room");
        btnDeallocate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDeallocateMouseClicked(evt);
            }
        });
        btnDeallocate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeallocateActionPerformed(evt);
            }
        });
        getContentPane().add(btnDeallocate);
        btnDeallocate.setBounds(320, 10, 150, 40);

        btnAddRoom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/add.png"))); // NOI18N
        btnAddRoom.setText("Add Room");
        btnAddRoom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddRoomMouseClicked(evt);
            }
        });
        btnAddRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddRoomActionPerformed(evt);
            }
        });
        getContentPane().add(btnAddRoom);
        btnAddRoom.setBounds(10, 10, 150, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSettingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSettingsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSettingsActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnAddUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddUserActionPerformed

    private void btnAlloteRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlloteRoomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAlloteRoomActionPerformed

    private void btnDeallocateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeallocateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeallocateActionPerformed

    private void btnRefreshMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRefreshMouseClicked
        DefaultTableModel tblModel = (DefaultTableModel)tblRooms.getModel();
        tblModel.setRowCount(0);
        refresh();
    }//GEN-LAST:event_btnRefreshMouseClicked

    private void btnAddUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddUserMouseClicked
        // TODO add your handling code here:
        AddUser addUser = new AddUser();
        addUser.setVisible(true);
    }//GEN-LAST:event_btnAddUserMouseClicked

    private void btnSettingsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSettingsMouseClicked
        // TODO add your handling code here:
        Settings settings = new Settings();
        settings.setVisible(true);
    }//GEN-LAST:event_btnSettingsMouseClicked

    private void btnAlloteRoomMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAlloteRoomMouseClicked
        // TODO add your handling code here:
        AlloteRoom alloteRoom = new AlloteRoom();
        alloteRoom.setVisible(true);
    }//GEN-LAST:event_btnAlloteRoomMouseClicked

    private void btnDeallocateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeallocateMouseClicked
        // TODO add your handling code here:
        DealloteRoom dealloate = new DealloteRoom();
        dealloate.setVisible(true);
    }//GEN-LAST:event_btnDeallocateMouseClicked

    private void btnAddRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddRoomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddRoomActionPerformed

    private void btnAddRoomMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddRoomMouseClicked
        AddRoom addRoom = new AddRoom();
        addRoom.setVisible(true);
    }//GEN-LAST:event_btnAddRoomMouseClicked

    private String getCurrentGuest(String id)
    {
        DbConnection dbinfo = new DbConnection();
        String dburl = dbinfo.dburl;
        String dbuser = dbinfo.dbuser;
        String dbuspass = dbinfo.dbuserpass;
        
        String currentguest = "";
        
        try ( Connection con = DriverManager.getConnection(dburl, dbuser, dbuspass)) {
            //here bauet_guestroom is database name, root is username and password
            //System.out.println("Database connected successfuly.");
            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery("SELECT * FROM `users` WHERE `id`='"+id+"'");
            
            while(rs.next()){
                currentguest = "#" + rs.getString(1) + " - " + rs.getString(2);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
        return currentguest;
    }
    
    private void refresh() {
        DbConnection dbinfo = new DbConnection();
        String dburl = dbinfo.dburl;
        String dbuser = dbinfo.dbuser;
        String dbuspass = dbinfo.dbuserpass;
        
        DefaultTableModel tblModel = (DefaultTableModel)tblRooms.getModel();
        
        try ( Connection con = DriverManager.getConnection(dburl, dbuser, dbuspass)) {
            //here bauet_guestroom is database name, root is username and password
            //System.out.println("Database connected successfuly.");
            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery("SELECT * FROM `rooms`");
            while(rs.next()){
                String roomId = rs.getString(1);
                String gender = rs.getString(2);
                String information = rs.getString(3);
                String fee = rs.getString(4);
                String status = rs.getString(5);
                String currentGuest = rs.getString(6);
                if(status.equals("1")){
                    currentGuest = getCurrentGuest(currentGuest);
                    status = "booked";
                } else {
                    status = "available";
                }
                
                String tbData[] = {roomId, gender, status, currentGuest, fee, information};
                tblModel.addRow(tbData);
                
            }
        } catch (SQLException ex) {
            Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddRoom;
    private javax.swing.JButton btnAddUser;
    private javax.swing.JButton btnAlloteRoom;
    private javax.swing.JButton btnDeallocate;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnSettings;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblRooms;
    // End of variables declaration//GEN-END:variables
}
